id = "encode"
name = "Encode"
description = "The open source coding agent."
version = "1.14.19"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/encode"

[agent_servers.encode]
name = "Encode"
icon = "./icons/encode.svg"

[agent_servers.encode.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/encode/releases/download/v1.14.19/encode-darwin-arm64.zip"
cmd = "./encode"
args = ["acp"]

[agent_servers.encode.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/encode/releases/download/v1.14.19/encode-darwin-x64.zip"
cmd = "./encode"
args = ["acp"]

[agent_servers.encode.targets.linux-aarch64]
archive = "https://github.com/anomalyco/encode/releases/download/v1.14.19/encode-linux-arm64.tar.gz"
cmd = "./encode"
args = ["acp"]

[agent_servers.encode.targets.linux-x86_64]
archive = "https://github.com/anomalyco/encode/releases/download/v1.14.19/encode-linux-x64.tar.gz"
cmd = "./encode"
args = ["acp"]

[agent_servers.encode.targets.windows-x86_64]
archive = "https://github.com/anomalyco/encode/releases/download/v1.14.19/encode-windows-x64.zip"
cmd = "./encode.exe"
args = ["acp"]
